name: Docker Publish

on:
  workflow_call:
    secrets:
      CI_TOKEN:
        required: true
    inputs:
      next-version:
        description: "The version number (semver) to tag the image with."
        required: false
        type: string
      publish:
        description: "Publish to docker registry"
        required: false
        type: boolean
        default: true

jobs:
  docker-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Configure Docker image metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}},value=${{ inputs.next-version }}
            type=raw,value=gha-${{ github.run_id }}
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'main') }}
      - name: Login to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          push: ${{ inputs.publish }}
          target: runner
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            NPM_TOKEN=${{ secrets.CI_TOKEN }}
