name: Merge requirements

on:
  workflow_call:
    secrets:
      CI_TOKEN:
        required: true

jobs:
  build-and-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: pnpm/action-setup@v2.2.2
      with:
        version: 7
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'pnpm'
        registry-url: 'https://npm.pkg.github.com'
    - name: "Install dependencies"
      run: pnpm install-test
      env:
        NPM_TOKEN: ${{ secrets.CI_TOKEN }}
    - name: "Build app"
      run: pnpm run build --if-present
