name: npm release

on:
  workflow_call:
    secrets:
      ci-token:
        required: true

jobs:
  release:
    name: npm release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      issues: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@dtnmr'
      - run: |
          npm set-script prepare ""
          npm ci
      - name: Release
        env:
          GH_TOKEN: ${{ secrets.ci-token }}
          NODE_AUTH_TOKEN: ${{ secrets.ci-token }}
        run: |
          npx semantic-release
          
