name: Semantic Release

on:
  workflow_call:
    secrets:
      CI_TOKEN:
        required: true
    outputs:
      next-version:
        description: "The next version number determined by semantic-release"
        value: ${{ jobs.semantic-release.next-version }}

jobs:
  semantic-release:
    outputs:
      next-version: ${{ steps.semantic.outputs.nextVersion }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      issues: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: 'https://npm.pkg.github.com'
          scope: '@eatcala'
      - run: npm ci --ignore-scripts
        env:
          NPM_TOKEN: ${{ secrets.CI_TOKEN }}
      - name: Run semantic-release
        id: semantic
        env:
          GH_TOKEN: ${{ secrets.CI_TOKEN }}
          NPM_TOKEN: ${{ secrets.CI_TOKEN }}
        run: |
          npx semantic-release
